### PR TITLE
Add contracts and contractItems, delete old fields in character_sheet

### PR DESCRIPTION
**Pull request by Chipsoid**
- add contracts, but not contract bids
- Add jump fatique and etc in Phoebe. 
- Delete clone fields in Rhea.

I have troubles with XML::Simple while parsing character_sheet api response. In this Pull Request we have problem with jump_clone_implants. If we have same implants in different clones - implant merges to last jump clone in response structure. 
May be this is good time to replace XML::Simple to XML::LibXML?

### CODE REVIEW

**Comment by bluefeet** [comment]
Ah, ya, looks like CREST is still under development and documentation is being written:
https://neweden-dev.com/Category:CREST

"CREST is the new API, that is yet to be fully released.
The are several public endpoints however."

**Comment by bluefeet** [comment]
OK, this is merged into master.  I had to rebase as your changes were not committed on top of the latest master.  Some tests are failing:

```
t/10_local.t .............. 1/?
#   Failed test 'API result matches dumped result for character_sheet'
#   at t/10_local.t line 83.
#     Structures begin differing at:
#          $got->{clone_type_id} = undef
#     $expected->{clone_type_id} = Does not exist

#   Failed test 'API result matches dumped result for contract_items'
#   at t/10_local.t line 83.
#     Structures begin differing at:
#          $got->{87229270}[0]{record_id} = '1457473351'
#     $expected->{87229270}[0]{record_id} = '1457473349'
# Looks like you failed 2 tests of 22.
t/10_local.t .............. Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/22 subtests
```

Can you fix?

**Comment by Chipsoid** [comment]
Oh, sorry. Fixed!

**Comment by bluefeet** [comment]
That fix was also not done ontop of the latest master, which may be why I'm still getting failures:

```
t/10_local.t .............. 1/?
#   Failed test 'API result matches dumped result for contract_items'
#   at t/10_local.t line 84.
#     Structures begin differing at:
#          $got->{87229270}[0]{record_id} = '1457473326'
#     $expected->{87229270}[0]{record_id} = '1457473349'
# Looks like you failed 1 test of 22.
t/10_local.t .............. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/22 subtests
```

I've cherry-picked that commit onto master.

**Comment by bluefeet** [comment]
Any chance you could check out the latest master and take a look?

**Comment by Chipsoid** [comment]
in 10-local.t was hack for loading module form my local directory. May be now is ok?
```
chips@ChipsComp:/www/Games-EveOnline-API$ git fetch upstream
remote: Counting objects: 35, done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 35 (delta 12), reused 29 (delta 10)
Unpacking objects: 100% (35/35), done.
From github.com:bluefeet/Games-EveOnline-API
   2527b23..2ecc0fc  master     -> upstream/master

chips@ChipsComp:/www/Games-EveOnline-API$ perl t/10_local.t
ok 1 - API result matches dumped result for skill_tree
ok 2 - API result matches dumped result for ref_types
ok 3 - API result matches dumped result for sovereignty
ok 4 - API result matches dumped result for characters
ok 5 - API result matches dumped result for character_sheet
ok 6 - API result matches dumped result for skill_in_training
ok 7 - API result matches dumped result for api_key_info
ok 8 - API result matches dumped result for account_status
ok 9 - API result matches dumped result for character_info
ok 10 - API result matches dumped result for asset_list
ok 11 - API result matches dumped result for contact_list
ok 12 - API result matches dumped result for wallet_transactions
ok 13 - API result matches dumped result for wallet_journal
ok 14 - API result matches dumped result for mail_lists
ok 15 - API result matches dumped result for mail_bodies
ok 16 - API result matches dumped result for mail_messages
ok 17 - API result matches dumped result for character_name
ok 18 - API result matches dumped result for character_ids
ok 19 - API result matches dumped result for station_list
ok 20 - API result matches dumped result for corporation_sheet
ok 21 - API result matches dumped result for contracts
ok 22 - API result matches dumped result for contract_items
1..22
```

**Comment by bluefeet** [comment]
Now its failing on the type_id:

```
t/10_local.t .............. 22/?
#   Failed test 'API result matches dumped result for contract_items'
#   at t/10_local.t line 83.
#     Structures begin differing at:
#          $got->{87229270}[0]{type_id} = '2488'
#     $expected->{87229270}[0]{type_id} = '3082'
# Looks like you failed 1 test of 22.
t/10_local.t .............. Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by Chipsoid** [comment]
Try again, please

**Comment by bluefeet** [comment]
Closing as this module is official deprecated.

**Pull request closed without merging**
